<?php 
	include('externas/head.php');
	include('externas/header.php');
	include('externas/menuDocente.php');
	include('externas/lateral.php');
	//include('externas/Clases/classConn.php');
 ?>
<title>Pre-Registro</title>	 
	<?php 
		include('externas/finalizarContenido.php')
?>
<?php 
		include('externas/footer.php');
?>