<?php 
	include('../../externas/head.php');
	include('../../externas/header.php');
	include('../../externas/menuInvest.php');
	include('../../externas/lateral.php');
	include('../../controladores/Clases/clase_consultas_seg_investigacion.php');
 ?>
	<title>Seguimiento</title>	 
<?php 
	include('../../externas/revisionEntregableInvest.php');
	include('../../externas/footer.php');
?>