<?php 
	include('../../externas/head.php');
	include('../../externas/header.php');
	include('../../externas/menuDocente.php');
	include('../../externas/lateral.php');
 ?>
	<title>Pre-Registro</title>	 
<?php 
	include('../../externas/registroComite.php');
?>
<?php 
	include('../../externas/footer.php');
?>