<?php 
	include('../../externas/head.php');
	include('../../externas/header.php');
	include('../../externas/menuComite.php');
	include('../../externas/lateral.php');
	include('../../controladores/Clases/clase_consultas_seg_comite.php');
 ?>
	<title>Seguimiento</title>	 
<?php 
	include('../../externas/revisionEntregableComite.php');
	include('../../externas/footer.php');
?>