<?php 
session_start();
	include('../../externas/head.php');
	include('../../externas/header.php');
	include('../../externas/menuGestion.php');
	include('../../externas/lateral.php');
 ?>
	<title>Pre-Registro</title>	 
<?php 
	include('../../externas/PreRegistroGestion.php')
?>
<?php 
	include('../../externas/footer.php');
?>