<?php 
	include('../../externas/head.php');
	include('../../externas/header.php');
	include('../../externas/menuGestion.php');
	include('../../externas/lateral.php');
	include('../../controladores/Clases/clase_consultas_seg_gestion.php');
 ?>
	<title>Seguimiento</title>	 
<?php 
	include('../../externas/revisionEntregableGest.php');
	include('../../externas/footer.php');
?>